apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "delivery-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: frontend
    {{- include "delivery-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
